---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: go-hey-kube
spec:
    replicas: 3
    selector:
        matchLabels:
            app: go-hey-kube
    template:
        metadata:
            labels:
                app: go-hey-kube
        spec:
            containers:
                - name: go-hey-kube
                  image: galihrivanto/go-hey-kube:1.0.0
                  imagePullPolicy: Always 
                  ports:
                    - containerPort: 8080
                  livenessProbe:
                    httpGet:
                        path: /health
                        port: 8080
                        scheme: HTTP
                    initialDelaySeconds: 5
                    periodSeconds: 15
                    timeoutSeconds: 5
                  readinessProbe:
                    httpGet:
                        path: /readiness
                        port: 8080
                        scheme: HTTP
                    initialDelaySeconds: 5
                    timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
    name: go-hey-kube-service
spec:
    type: NodePort
    ports:
        - name: http
          port: 9090
          targetPort: 8080
    selector:
        app: go-hey-kube 